code-insiders --install-extension beaugunderson.solidity-extended
code-insiders --install-extension golang.go
code-insiders --install-extension hosho.solidity-debugger
code-insiders --install-extension ipedrazas.kubernetes-snippets
code-insiders --install-extension JuanBlanco.solidity
code-insiders --install-extension lunuan.kubernetes-templates
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code-insiders --install-extension ms-python.isort
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-python.vscode-pylance
code-insiders --install-extension ms-toolsai.jupyter
code-insiders --install-extension ms-toolsai.jupyter-keymap
code-insiders --install-extension ms-toolsai.jupyter-renderers
code-insiders --install-extension ms-toolsai.vscode-jupyter-cell-tags
code-insiders --install-extension ms-toolsai.vscode-jupyter-slideshow
code-insiders --install-extension ms-vscode-remote.remote-containers
code-insiders --install-extension ms-vscode-remote.remote-ssh
code-insiders --install-extension ms-vscode-remote.remote-ssh-edit
code-insiders --install-extension ms-vscode-remote.remote-wsl
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
code-insiders --install-extension ms-vscode.makefile-tools
code-insiders --install-extension ms-vscode.remote-explorer
code-insiders --install-extension ms-vscode.remote-server
code-insiders --install-extension octref.vetur
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension shd101wyy.markdown-preview-enhanced
code-insiders --install-extension SimonSiefke.prettier-vscode
